FROM node:18-alpine AS frontend

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . . 

RUN npm run build

FROM nginx:alpine

COPY --from=frontend /app/dist /usr/share/nginx/html

CMD [ "nginx", "-g", "daemon off;" ]